# Generated by Django 4.2.7 on 2024-12-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mainpageinfoblock_delete_mainpageadvertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageinfoblock',
            name='block_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
    ]
