# Generated by Django 4.2.7 on 2025-01-19 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_alter_product_options'),
        ('core', '0005_alter_mainpageinfoblock_block_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageinfoblock',
            name='block_header',
            field=models.CharField(default='', max_length=128, verbose_name='Заголовок рекламного блока'),
        ),
        migrations.AlterField(
            model_name='mainpageinfoblock',
            name='block_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Товар для рекламы на главной странице'),
        ),
        migrations.AlterField(
            model_name='mainpageinfoblock',
            name='block_name',
            field=models.CharField(default='', max_length=128, verbose_name='Название рекламного блока'),
        ),
    ]
