# Generated by Django 4.2.7 on 2025-02-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mainpageinfoblock_block_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageinfoblock',
            name='block_brand',
            field=models.CharField(default='', max_length=128, verbose_name='Название бренда | Поле над заголовком | Опционально'),
        ),
        migrations.AlterField(
            model_name='mainpageinfoblock',
            name='block_header',
            field=models.CharField(default='', max_length=128, verbose_name='Заголовок рекламного блока | Отображается на странице'),
        ),
        migrations.AlterField(
            model_name='mainpageinfoblock',
            name='block_name',
            field=models.CharField(default='', max_length=128, verbose_name='Название рекламного блока | Служебная информация'),
        ),
    ]
