# Generated by Django 4.2.7 on 2025-02-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_mainpageinfoblock_block_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageinfoblock',
            name='block_brand',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Название бренда | Поле над заголовком | Опционально'),
        ),
    ]
