# Generated by Django 4.2.7 on 2025-02-12 16:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Краткое описание')),
                ('full_description', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Полное описание')),
                ('place', models.IntegerField(blank=True, default=0, null=True, verbose_name='Место в списке')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Активен'), ('ARCHIVED', 'В архиве')], default='DRAFT', verbose_name='Статус показа на страницах')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Бренд')),
                ('logo', models.ImageField(blank=True, default='', upload_to='brand/logo', verbose_name='Логотип бренда')),
                ('banner', models.ImageField(blank=True, default='', upload_to='brand/banner', verbose_name='Баннер бренда')),
                ('banner_color', models.CharField(default='#3391c5', max_length=32, null=True, verbose_name='Цвет баннера бренда')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='url-адрес')),
                ('title', models.TextField(blank=True, default='', null=True, verbose_name='Title бренда')),
                ('ceo_description', models.TextField(blank=True, default='', null=True, verbose_name='CEO Description')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['place'],
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, verbose_name='Имя специалиста')),
                ('phone', models.CharField(max_length=28, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=56, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Краткое описание')),
                ('full_description', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Полное описание')),
                ('place', models.IntegerField(blank=True, default=0, null=True, verbose_name='Место в списке')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Активен'), ('ARCHIVED', 'В архиве')], default='DRAFT', verbose_name='Статус показа на страницах')),
                ('name', models.CharField(max_length=256, verbose_name='Название | Заголовок')),
                ('characteristics', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Характеристики')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='category/logo', verbose_name='Логотип')),
                ('banner', models.ImageField(blank=True, default='', upload_to='category/banner', verbose_name='Баннер')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='url-адрес')),
                ('title', models.TextField(blank=True, default='', null=True, verbose_name='Title страницы')),
                ('keywords', models.TextField(blank=True, default='', null=True, verbose_name='Keywords')),
                ('ceo_description', models.TextField(blank=True, default='', null=True, verbose_name='CEO Description')),
                ('is_final', models.BooleanField(default=False, verbose_name='Отметка о том, что категория является финальной и в ней содержатся товары')),
                ('youtube_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на YouTube')),
                ('rutube_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка Rutube')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand', verbose_name='Бренд, к которому относится категория')),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='catalog.category', verbose_name='Родительские категории')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.specialist', verbose_name='Специалист, ответственный за категорию')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['place'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.category',),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Краткое описание')),
                ('full_description', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Полное описание')),
                ('place', models.IntegerField(blank=True, default=0, null=True, verbose_name='Место в списке')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Активен'), ('ARCHIVED', 'В архиве')], default='DRAFT', verbose_name='Статус показа на страницах')),
                ('name', models.CharField(max_length=128, verbose_name='Артикул')),
                ('text_description', models.TextField(blank=True, default='', null=True, verbose_name='Краткое описание (текст)')),
                ('shipping_pack', models.CharField(blank=True, max_length=10, null=True, verbose_name='Количество в упаковке')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer', to='catalog.product', verbose_name='Товар, к которому принадлежит код')),
            ],
            options={
                'verbose_name': 'Код',
                'verbose_name_plural': 'Коды',
                'ordering': ['name'],
            },
        ),
    ]
