# Generated by Django 4.2.7 on 2025-01-27 10:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, verbose_name='Имя специалиста')),
                ('phone', models.CharField(max_length=28, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=56, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.category',),
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['place'], 'verbose_name': 'Код', 'verbose_name_plural': 'Коды'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='instruction',
        ),
        migrations.AddField(
            model_name='brand',
            name='banner_color',
            field=models.CharField(default='#3391c5', max_length=32, null=True, verbose_name='Цвет баннера бренда'),
        ),
        migrations.AddField(
            model_name='brand',
            name='full_description',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='characteristics',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='category',
            name='full_description',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='category',
            name='rt_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка Rutube'),
        ),
        migrations.AddField(
            model_name='category',
            name='ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер РУ'),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Title страницы'),
        ),
        migrations.AddField(
            model_name='category',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='category/videos', verbose_name='Видео файл'),
        ),
        migrations.AddField(
            model_name='category',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на YouTube'),
        ),
        migrations.AddField(
            model_name='offer',
            name='characteristics',
            field=models.FileField(blank=True, default='', null=True, upload_to='characteristics/', verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='offer',
            name='full_description',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='offer',
            name='shipping_pack',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Количество в упаковке'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название категории | Заголовок'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.specialist', verbose_name='Специалист, ответственный за категорию'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer', to='catalog.product', verbose_name='Категория, к которой принадлежит товар'),
        ),
    ]
