# Generated by Django 4.2.7 on 2024-12-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_category_video_file_category_video_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='category',
            name='vk_url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='category',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Видео или ссылка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='video_type',
            field=models.CharField(blank=True, choices=[('file', 'Файл'), ('youtube', 'YouTube'), ('vkontacte', 'ВКонтакте')], max_length=20, null=True, verbose_name='Тип видео'),
        ),
    ]
