# Generated by Django 4.2.7 on 2024-12-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_category_video_file_remove_category_vk_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='video',
        ),
        migrations.AddField(
            model_name='category',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео файл'),
        ),
        migrations.AddField(
            model_name='category',
            name='vkontacte_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на ВКонтакте'),
        ),
        migrations.AddField(
            model_name='category',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на YouTube'),
        ),
    ]
