# Generated by Django 4.2.7 on 2024-12-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_category_video_category_video_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='vkontacte_link',
            new_name='vk_link',
        ),
        migrations.RemoveField(
            model_name='category',
            name='video_type',
        ),
    ]
