# Generated by Django 4.2.7 on 2024-12-19 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_rename_vkontacte_link_category_vk_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, verbose_name='Имя специалиста')),
                ('phone', models.CharField(max_length=28, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=56, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.specialist', verbose_name='Специалист, ответственный за категорию'),
        ),
    ]
