# Generated by Django 4.2.7 on 2024-12-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_specialist_category_specialist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='vk_link',
        ),
        migrations.AddField(
            model_name='category',
            name='rt_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка Rutube'),
        ),
    ]
