# Generated by Django 4.2.7 on 2024-12-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_category_vk_link_category_rt_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='category/videos', verbose_name='Видео файл'),
        ),
    ]
