# Generated by Django 4.2.7 on 2024-12-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_category_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, default='<ul>\n                    <li><span>Оссобенность 1</span>\xa0</li>\n                    <li><span>Особенность 2</span></li>\n                </ul>', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='<ul>\n                    <li><span>Оссобенность 1</span>\xa0</li>\n                    <li><span>Особенность 2</span></li>\n                </ul>', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, default='<ul>\n                    <li><span>Оссобенность 1</span>\xa0</li>\n                    <li><span>Особенность 2</span></li>\n                </ul>', null=True, verbose_name='Описание'),
        ),
    ]
