# Generated by Django 4.2.7 on 2024-12-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_brand_description_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер РУ'),
        ),
    ]
