# Generated by Django 4.2.7 on 2024-12-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_brand_description_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='full_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='full_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='offer',
            name='characteristics',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='offer',
            name='full_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Краткое описание'),
        ),
    ]
