# Generated by Django 4.2.7 on 2024-12-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_category_db_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='metadesciption',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание для метатега'),
        ),
    ]
