# Generated by Django 4.2.7 on 2024-12-25 07:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_rename_metadesciption_category_metadescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='custom_description',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Кастомное описание'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='full_description',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='custom_description',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Кастомное описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='full_description',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='custom_description',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Кастомное описание'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='full_description',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Полное описание'),
        ),
    ]
