# Generated by Django 4.2.7 on 2025-01-19 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_brand_custom_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='product', serialize=False, to='catalog.category', verbose_name='Финальная категория')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Название категории')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='product/logo', verbose_name='Логотип продукта')),
                ('banner', models.ImageField(blank=True, default='', upload_to='product/banner', verbose_name='Баннер продукта')),
                ('metadescription', models.TextField(blank=True, default='', null=True, verbose_name='Описание для метатега')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='product/videos', verbose_name='Видео файл')),
                ('youtube_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на YouTube')),
                ('rt_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка Rutube')),
                ('ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер РУ')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Описание продукта')),
                ('place', models.PositiveIntegerField(default=0, verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['place'],
            },
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['place'], 'verbose_name': 'Код', 'verbose_name_plural': 'Коды'},
        ),
    ]
