# Generated by Django 4.2.7 on 2025-01-19 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_product_alter_offer_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.category',),
        ),
    ]
