# Generated by Django 4.2.7 on 2025-01-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_remove_brand_custom_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='metadescription',
        ),
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Title страницы'),
        ),
    ]
