# Generated by Django 4.2.7 on 2025-01-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_remove_category_metadescription_category_keywords_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
