# Generated by Django 4.2.7 on 2025-01-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='characteristics',
            field=models.FileField(blank=True, default='', null=True, upload_to='characteristics/', verbose_name='Характеристики'),
        ),
    ]
