# Generated by Django 4.2.7 on 2025-01-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_alter_offer_characteristics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='place',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Место в списке'),
        ),
        migrations.AlterField(
            model_name='category',
            name='place',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Место в списке'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='place',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Место в списке'),
        ),
    ]
