# Generated by Django 4.2.7 on 2025-01-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_alter_brand_place_alter_category_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='text_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Краткое описание (текст)'),
        ),
        migrations.AddField(
            model_name='offer',
            name='text_full_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Полное описание (текст)'),
        ),
    ]
