# Generated by Django 4.2.7 on 2025-02-01 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_offer_text_description_offer_text_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='banner',
            field=models.ImageField(blank=True, default='', upload_to='category/banner', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='category/logo', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer', to='catalog.product', verbose_name='Товар, к которому принадлежит код'),
        ),
    ]
