# Generated by Django 4.2.7 on 2025-02-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_alter_category_banner_alter_category_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_color',
            field=models.CharField(default='#3391c5', max_length=32, null=True, verbose_name='Цвет баннера бренда'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название | Заголовок'),
        ),
    ]
