# Generated by Django 4.2.7 on 2025-05-04 11:37

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_category_banner_color_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='full_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='characteristics',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='full_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='full_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Полное описание'),
        ),
    ]
