# Generated by Django 4.2.7 on 2025-02-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='product/catalog', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='instructionsfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='product/instructions', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='product/certificates', verbose_name='Файл'),
        ),
    ]
