# Generated by Django 4.2.7 on 2025-01-27 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_specialist_product_alter_offer_options_and_more'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelfile',
            options={'verbose_name': 'РУ и Сертификат', 'verbose_name_plural': 'РУ и Сертификаты'},
        ),
        migrations.AlterModelOptions(
            name='modelimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.RemoveField(
            model_name='modelfile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='modelimage',
            name='category',
        ),
        migrations.AddField(
            model_name='modelfile',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='modelimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='category/certificates', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='modelimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/images', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='InstructionsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='category/instructions', verbose_name='Файл')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Инструкция',
                'verbose_name_plural': 'Инструкции',
            },
        ),
        migrations.CreateModel(
            name='CatalogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='category/catalog', verbose_name='Файл')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Файл каталога',
                'verbose_name_plural': 'Каталог',
            },
        ),
    ]
