# Generated by Django 4.2.7 on 2024-12-19 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_category_vk_link_category_rt_link'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFileVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='category/videos')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
