# Generated by Django 4.2.7 on 2024-12-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_modelfilevideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelFileVideo',
        ),
    ]
