# Generated by Django 4.2.7 on 2025-01-19 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_delete_product_product'),
        ('files', '0004_alter_modelfile_options_instructionsfile_catalogfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogfile',
            options={'verbose_name': 'Файл каталога', 'verbose_name_plural': 'Каталог'},
        ),
        migrations.AlterModelOptions(
            name='instructionsfile',
            options={'verbose_name': 'Инструкция', 'verbose_name_plural': 'Инструкции'},
        ),
        migrations.AlterModelOptions(
            name='modelfile',
            options={'verbose_name': 'РУ и Сертификат', 'verbose_name_plural': 'РУ и Сертификаты'},
        ),
        migrations.AlterModelOptions(
            name='modelimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.RemoveField(
            model_name='catalogfile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='instructionsfile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='modelfile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='modelimage',
            name='category',
        ),
        migrations.AddField(
            model_name='catalogfile',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='instructionsfile',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='modelfile',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='modelimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='catalogfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='category/catalog', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='instructionsfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='category/instructions', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='category/certificates', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='modelimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/images', verbose_name='Изображение'),
        ),
    ]
