apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  PYTHONPATH: /NDA2024-1
  DJANGO_SETTINGS_MODULE: nda.settings
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    
    scrape_configs:
      - job_name: 'django'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['web:8000']
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            replacement: django_app
        scrape_timeout: 10s
    
      - job_name: 'postgres'
        static_configs:
          - targets: ['postgres-exporter:9187']